name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Cargo test
        env:
          RUST_BACKTRACE: 1
        run: cargo test --all --all-features

  python:
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build release binary
        run: cargo build --release
      - name: Install QA dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r qa/requirements.txt
      - name: Run Python QA tests
        env:
          GTO_TRAINER_BIN: ./target/release/gto-trainer
        run: |
          ./target/release/gto-trainer serve --addr 127.0.0.1:8080 &
          SERVER_PID=$!
          trap "kill $SERVER_PID" EXIT
          python -m pytest qa/tests

  browser:
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install NPM dependencies
        run: npm ci
      - name: Build release binary
        run: cargo build --release
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          GTO_TRAINER_HOST: 127.0.0.1
          GTO_TRAINER_PORT: 8082
        run: npm test
