name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13.5
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        run: uv sync --locked --extra dev
      - name: Install Playwright browsers
        run: uv run --locked --extra dev -- python -m playwright install --with-deps chromium
      - name: Lint
        run: |
          uv run --locked --extra dev -- ruff format --check .
          uv run --locked --extra dev -- ruff check .
      - name: Test
        run: uv run --locked --extra dev -- pytest -q
