name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7'
      - name: Cache uv environment
        id: cache-uv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('uv.lock') }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        env:
          UV_DEFAULT_INDEX: https://pypi.org/simple
        run: uv sync --locked --extra dev --preview-features extra-build-dependencies
      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        env:
          UV_DEFAULT_INDEX: https://pypi.org/simple
        run: uv run --locked --extra dev -- python -m playwright install --with-deps chromium
      - name: Lint
        env:
          UV_DEFAULT_INDEX: https://pypi.org/simple
        run: |
          uv run --locked --extra dev -- ruff format --check .
          uv run --locked --extra dev -- ruff check .
      - name: Test
        env:
          UV_DEFAULT_INDEX: https://pypi.org/simple
        run: uv run --locked --extra dev -- pytest -q
